# Generated by Django 3.2.6 on 2022-02-17 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
